### ISSUE TITLE
Consider adjustment of DispatcherConfiguration interface

### ISSUE THREAD

**Issue by fpt-nessian** [goodees/goodees#1]
Why:

When using DispatcherConfiguration, I was immediately stuck by the fact that I need to implement execute method (Like what, configuration has some business method it performs?).

It might be more readable and comprehensible to explicitly (via interface) force the client to provide method in a from of functional interface, for instance TriConsumer<String, Request<RS>, BiConsumer<RS,Throwable>>.

**Comment by pdudits** [comment]
I added default implementation that separates static dependencies (executors) from strategies (execution, retry) in #2.

How would you like such helper implementation class, @fpt-nessian?

**Comment by pdudits** [comment]
I think you really meant to close it 😉
