### ISSUE TITLE
Payara 163 Issues

### ISSUE THREAD

**Issue by gitgraves** [goodees/goodees#3]
Great tool thank you for publishing.  Seems to fail against Payara 163 however.

**Comment by pdudits** [comment]
If you specified what is the error you're getting I might be able to help, I think I used it in 2016 already. 

However 163 is quite old and had quite some issues with asadmin, therefore the script might fail

**Comment by gitgraves** [comment]
My bad, I meant the latest version 183.  Closing this issue, apologies.  I will open a new issue, but essentially after install it enters a loop and generates tons of output.
